[project]
name = "capstoneproject"
version = "0.1.0"
description = ""
authors = [
    {name = "ngovandong", email = "dongngo2001@gmail.com"}
]
requires-python = ">=3.11"
dependencies = [
    "django>=4.2.0,<5.0.0",
    "djangorestframework>=3.15.0,<4.0.0",
    "django-debug-toolbar>=4.2.0,<5.0.0",
    "djangorestframework-simplejwt>=5.3.0,<6.0.0",
    "django-cors-headers>=4.3.0,<5.0.0",
    "python-dotenv>=1.0.0,<2.0.0",
    "requests>=2.31.0,<3.0.0",
    "pillow>=10.0.0,<11.0.0",
    "drf-yasg>=1.21.7,<2.0.0",
    "cloudinary>=1.40.0,<2.0.0",
    "gunicorn>=21.2.0,<22.0.0",
    "mysqlclient>=2.2.0,<3.0.0",
    "django-rq>=2.10.0,<3.0.0",
    "elasticsearch>=8.11.0,<9.0.0",
    "elasticsearch-dsl>=8.11.0,<9.0.0",
    "django-elasticsearch-dsl>=8.0.0,<9.0.0",
    "django-redis>=5.4.0,<6.0.0",
    "beautifulsoup4>=4.12.0,<5.0.0",
    "django-revproxy>=0.12.0,<1.0.0",
    "channels[daphne]>=4.0.0",
    "channels-redis>=4.0.0",
]

[project.optional-dependencies]
dev = [
    "autopep8>=2.1.0,<3.0.0",
]
