from .course import CourseViewSet
from .crawler import GetImagesUrlView
from .deck import DeckViewSet
from .folder import FolderViewSet
from .grammar import GrammarViewSet
from .learning import LearningViewSet
from .listening import ListeningViewSet
from .reminders import ReminderViewSet
from .role import RoleViewSet
from .speaking import SpeakingViewSet
from .term import TermViewSet
from .translate import TranslateView
from .user import UserViewSet
from .writing import WritingViewSet
