from .course import CourseViewSet
from .crawler import GetImagesUrlView
from .deck import DeckViewSet
from .folder import FolderViewSet
from .learning import LearningViewSet
from .reminders import ReminderViewSet
from .role import RoleViewSet
from .speaking import SpeakingViewSet
from .term import TermViewSet
from .translate import TranslateView
from .user import UserViewSet
