# Generated by Django 4.1.5 on 2023-03-12 02:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0002_userlearningprogress_userdeckrole_deck_users"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deck",
            name="owner",
        ),
        migrations.AlterField(
            model_name="deck",
            name="users",
            field=models.ManyToManyField(
                related_name="decks", through="backend.UserDeckRole", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
