# Generated by Django 4.1.5 on 2023-03-14 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_rename_user_role_userdeckrole_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='owner',
            field=models.ForeignKey(default='239a570507a14ade9e53c017e65592d9', on_delete=django.db.models.deletion.CASCADE, related_name='my_own_decks', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdeckrole',
            name='role',
            field=models.CharField(choices=[('E', 'Edit'), ('V', 'ViewOnly')], max_length=1),
        ),
    ]
