# Generated by Django 4.1.5 on 2023-03-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0007_deck_owner_alter_userdeckrole_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
    ]
