# Generated by Django 4.1.5 on 2023-03-14 15:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0008_user_is_superuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_staff",
        ),
    ]
