# Generated by Django 4.1.5 on 2023-03-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_deck_visible_alter_userdeckrole_streaks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='visible',
        ),
        migrations.AddField(
            model_name='deck',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
