# Generated by Django 4.1.5 on 2023-03-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_deck_background_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='background_url',
            field=models.URLField(),
        ),
    ]
