# Generated by Django 4.1.5 on 2023-03-20 15:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_remove_deck_background_url_deck_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='background',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
