# Generated by Django 4.1.7 on 2023-03-23 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_alter_deck_background'),
    ]

    operations = [
        migrations.RenameField(
            model_name='term',
            old_name='term',
            new_name='name',
        ),
    ]
