# Generated by Django 4.1.7 on 2023-03-23 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_rename_term_term_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='term',
            old_name='image_url',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='term',
            old_name='name',
            new_name='term',
        ),
    ]
