# Generated by Django 4.1.7 on 2023-03-23 09:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0018_rename_image_url_term_image_rename_name_term_term"),
    ]

    operations = [
        migrations.RenameField(
            model_name="term",
            old_name="term",
            new_name="name",
        ),
    ]
