# Generated by Django 4.1.5 on 2023-04-13 10:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_rename_term_term_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdeckrole',
            name='last_term_learned_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
