# Generated by Django 4.1.5 on 2023-04-13 13:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0020_userdeckrole_last_term_learned_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userdeckrole",
            name="last_term_learned_id",
        ),
    ]
