# Generated by Django 4.1.5 on 2023-04-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_remove_userdeckrole_last_term_learned_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlearningprogress',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
