# Generated by Django 4.1.5 on 2023-04-23 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_alter_userlearningprogress_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlearningprogress',
            options={'ordering': ('last_learned_at',)},
        ),
        migrations.AddField(
            model_name='folder',
            name='decks',
            field=models.ManyToManyField(related_name='folders', to='backend.deck'),
        ),
    ]
