# Generated by Django 4.1.5 on 2023-05-06 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0023_alter_userlearningprogress_options_folder_decks"),
    ]

    operations = [
        migrations.AddField(
            model_name="deck",
            name="default_deck",
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="backend.deck"
            ),
        ),
    ]
