# Generated by Django 4.1.5 on 2023-05-06 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_deck_default_deck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='default_deck',
        ),
        migrations.AddField(
            model_name='user',
            name='default_deck',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.deck'),
        ),
    ]
