# Generated by Django 4.1.5 on 2023-05-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0026_alter_term_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="term",
            name="image",
            field=models.TextField(blank=True, null=True),
        ),
    ]
