# Generated by Django 4.1.5 on 2023-05-28 02:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0027_alter_term_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="term",
            options={"ordering": ["created_at"]},
        ),
        migrations.AddField(
            model_name="term",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="term",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
