# Generated by Django 4.1.5 on 2023-06-16 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0028_alter_term_options_term_created_at_term_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="default_deck",
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="backend.deck"
            ),
        ),
    ]
