# Generated by Django 4.1.5 on 2023-06-16 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_alter_user_default_deck'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deck',
            options={'ordering': ('created_at',)},
        ),
    ]
