# Generated by Django 4.1.5 on 2023-07-05 00:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0029_userlearningprogress_is_skip"),
        ("backend", "0030_alter_deck_options"),
    ]

    operations = []
