# Generated by Django 4.1.5 on 2023-07-05 00:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_merge_20230705_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlearningprogress',
            name='last_revised_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 7, 5, 0, 17, 32, 46053)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userlearningprogress',
            name='last_learned_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
