# Generated by Django 4.2.23 on 2026-06-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0035_user_learning_streak_remove_role_streaks"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlearningprogress",
            name="total_revisions",
            field=models.IntegerField(default=0),
        ),
    ]
