# Generated by Django 4.2.23 on 2026-06-14 08:32

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import backend.shared.infrastructure.sqlalchemy.tables

# The user FK to backend_user is added separately because legacy tables in this
# database use the utf8mb3 charset while new tables inherit the server default
# (utf8mb4). MySQL rejects a foreign key whose column charset/collation differs
# from the referenced column, so we create the user_id column with the *same*
# collation as backend_user.id, whatever it happens to be in this database.
_USER_FK_TABLES = (
    ("backend_speakingconversation", "spk_conv_user_id_fk"),
    ("backend_speakinganalysis", "spk_analysis_user_id_fk"),
)


def add_user_fk(apps, schema_editor):
    connection = schema_editor.connection
    if connection.vendor == "mysql":
        with connection.cursor() as cursor:
            cursor.execute(
                "SELECT CHARACTER_SET_NAME, COLLATION_NAME FROM INFORMATION_SCHEMA.COLUMNS "
                "WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'backend_user' AND COLUMN_NAME = 'id'"
            )
            charset, collation = cursor.fetchone()
            for table, fk_name in _USER_FK_TABLES:
                cursor.execute(
                    f"ALTER TABLE `{table}` "
                    f"ADD COLUMN `user_id` char(32) CHARACTER SET {charset} COLLATE {collation} NOT NULL"
                )
                cursor.execute(
                    f"ALTER TABLE `{table}` ADD CONSTRAINT `{fk_name}` "
                    f"FOREIGN KEY (`user_id`) REFERENCES `backend_user` (`id`)"
                )
        return

    # Non-MySQL fallback (e.g. local sqlite): add the FK column the normal way.
    for model_name in ("speakingconversation", "speakinganalysis"):
        model = apps.get_model("backend", model_name)
        schema_editor.add_field(model, model._meta.get_field("user"))


def drop_user_fk(apps, schema_editor):
    connection = schema_editor.connection
    if connection.vendor == "mysql":
        with connection.cursor() as cursor:
            for table, fk_name in _USER_FK_TABLES:
                cursor.execute(f"ALTER TABLE `{table}` DROP FOREIGN KEY `{fk_name}`")
                cursor.execute(f"ALTER TABLE `{table}` DROP COLUMN `user_id`")
        return

    for model_name in ("speakingconversation", "speakinganalysis"):
        model = apps.get_model("backend", model_name)
        schema_editor.remove_field(model, model._meta.get_field("user"))


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0038_term_word_forms_word_family"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpeakingConversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("topic", models.CharField(blank=True, max_length=255)),
                ("context", models.TextField(blank=True)),
                ("accent", models.CharField(blank=True, max_length=8)),
                ("level", models.CharField(blank=True, max_length=8)),
                ("tone", models.CharField(blank=True, max_length=32)),
                ("lines", models.JSONField(blank=True, default=list)),
            ],
            options={
                "ordering": ["-created_at"],
            },
            bases=(backend.shared.infrastructure.sqlalchemy.tables.SQLAlchemyTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name="SpeakingAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("single", "Single sentence"), ("full", "Full session")],
                        default="single",
                        max_length=16,
                    ),
                ),
                ("target_text", models.TextField(blank=True)),
                ("transcription", models.TextField(blank=True)),
                ("accuracy_score", models.PositiveIntegerField(default=0)),
                ("fluency_score", models.PositiveIntegerField(default=0)),
                ("completeness_score", models.PositiveIntegerField(default=0)),
                ("rhythm_score", models.PositiveIntegerField(default=0)),
                ("words_per_minute", models.PositiveIntegerField(default=0)),
                ("accent_analysis", models.TextField(blank=True)),
                ("overall_feedback", models.TextField(blank=True)),
                ("key_struggles", models.JSONField(blank=True, default=list)),
                ("word_analysis", models.JSONField(blank=True, default=list)),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analyses",
                        to="backend.speakingconversation",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
            bases=(backend.shared.infrastructure.sqlalchemy.tables.SQLAlchemyTableMixin, models.Model),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="speakingconversation",
                    name="user",
                    field=models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speaking_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                    preserve_default=False,
                ),
                migrations.AddField(
                    model_name="speakinganalysis",
                    name="user",
                    field=models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speaking_analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                    preserve_default=False,
                ),
            ],
            database_operations=[
                migrations.RunPython(add_user_fk, drop_user_fk),
            ],
        ),
    ]
