# Generated by Django 4.2.23 on 2026-06-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0040_speakingaudioclip"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="speakingconversation",
            options={"ordering": ["-starred", "-created_at"]},
        ),
        migrations.AddField(
            model_name="speakingconversation",
            name="starred",
            field=models.BooleanField(default=False),
        ),
    ]
