# Generated by Django 4.2.23 on 2026-06-14 10:51

import uuid

from django.db import migrations, models

import backend.shared.infrastructure.sqlalchemy.tables


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0041_alter_speakingconversation_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AiResponseCache",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("context", models.CharField(db_index=True, max_length=32)),
                ("request_hash", models.CharField(db_index=True, max_length=64)),
                ("response", models.JSONField(default=dict)),
            ],
            bases=(backend.shared.infrastructure.sqlalchemy.tables.SQLAlchemyTableMixin, models.Model),
        ),
        migrations.AddField(
            model_name="speakingconversation",
            name="highlights",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddConstraint(
            model_name="airesponsecache",
            constraint=models.UniqueConstraint(fields=("context", "request_hash"), name="uniq_ai_cache_ctx_hash"),
        ),
    ]
