# Generated by Django 4.2.23 on 2026-06-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0045_drop_course_fcc_audio"),
    ]

    operations = [
        migrations.AddField(
            model_name="courselesson",
            name="background",
            field=models.CharField(blank=True, default="", max_length=160),
        ),
    ]
