# Generated by Django 4.2.23 on 2026-07-05 04:36

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import backend.shared.infrastructure.sqlalchemy.tables


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0052_usercourselessonprogress_last_dictation"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListeningTopic",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=160, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("level", models.CharField(blank=True, max_length=16)),
                ("description", models.TextField(blank=True)),
                ("source", models.CharField(blank=True, max_length=64)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "title"],
            },
            bases=(backend.shared.infrastructure.sqlalchemy.tables.SQLAlchemyTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ListeningProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("exercise_key", models.CharField(db_index=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("in_progress", "In progress"), ("completed", "Completed")],
                        default="in_progress",
                        max_length=16,
                    ),
                ),
                ("best_score", models.PositiveIntegerField(default=0)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_result", models.JSONField(blank=True, default=dict)),
                ("highlights", models.JSONField(blank=True, default=list)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listening_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
            bases=(backend.shared.infrastructure.sqlalchemy.tables.SQLAlchemyTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ListeningExercise",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=200)),
                ("key", models.CharField(max_length=255, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("level", models.CharField(blank=True, max_length=16)),
                ("order", models.PositiveIntegerField(default=0)),
                ("source_id", models.CharField(blank=True, max_length=64)),
                ("full_audio_url", models.CharField(blank=True, default="", max_length=500)),
                ("sentences", models.JSONField(blank=True, default=list)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="backend.listeningtopic",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
            bases=(backend.shared.infrastructure.sqlalchemy.tables.SQLAlchemyTableMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name="listeningprogress",
            constraint=models.UniqueConstraint(
                fields=("user", "exercise_key"), name="uniq_user_listening_exercise_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="listeningexercise",
            constraint=models.UniqueConstraint(fields=("topic", "slug"), name="uniq_listening_exercise_slug"),
        ),
    ]
