# Generated by Django 4.2.23 on 2026-07-05 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0053_listeningtopic_listeningprogress_listeningexercise_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listeningtopic",
            name="background",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
