# Generated by Django 4.2.23 on 2026-07-08 17:38

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import backend.shared.infrastructure.sqlalchemy.tables


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0056_grammar_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviseCard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("vocab", "Vocabulary"),
                            ("grammar", "Grammar"),
                            ("listening", "Listening"),
                            ("speaking", "Speaking"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("ref", models.CharField(db_index=True, max_length=255)),
                ("prompt", models.TextField(blank=True)),
                ("answer", models.TextField(blank=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("severity", models.PositiveIntegerField(default=1)),
                ("mistake_count", models.PositiveIntegerField(default=0)),
                ("correct_streak", models.PositiveIntegerField(default=0)),
                ("seen_count", models.PositiveIntegerField(default=0)),
                ("last_wrong_at", models.DateTimeField(blank=True, null=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("priority", models.FloatField(db_index=True, default=0.0)),
                ("mastered", models.BooleanField(db_index=True, default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revise_cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "-updated_at"],
            },
            bases=(backend.shared.infrastructure.sqlalchemy.tables.SQLAlchemyTableMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name="revisecard",
            constraint=models.UniqueConstraint(fields=("user", "kind", "ref"), name="uniq_revise_card_user_kind_ref"),
        ),
    ]
