# Generated by Django 4.2.23 on 2026-07-14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0057_revisecard_revisecard_uniq_revise_card_user_kind_ref"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Folder",
        ),
    ]
