# Generated by Django 5.2.16 on 2026-07-14 15:33

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import backend.shared.infrastructure.sqlalchemy.tables
import base.models.custom_model


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0059_alter_airesponsecache_id_alter_course_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompetitionScore",
            fields=[
                (
                    "id",
                    base.models.custom_model.Char32UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("game_key", models.CharField(db_index=True, max_length=16)),
                ("score", models.IntegerField(default=0)),
                (
                    "deck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competition_scores",
                        to="backend.deck",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competition_scores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-score", "-updated_at"),
                "constraints": [
                    models.UniqueConstraint(fields=("user", "deck", "game_key"), name="uniq_competition_user_deck_game")
                ],
            },
            bases=(backend.shared.infrastructure.sqlalchemy.tables.SQLAlchemyTableMixin, models.Model),
        ),
    ]
