# Generated by Django 5.2.16 on 2026-09-04 03:30

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import backend.shared.infrastructure.sqlalchemy.tables
import base.models.custom_model


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0060_competitionscore"),
    ]

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    base.models.custom_model.Char32UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("course_lesson", "Course lesson"),
                            ("listening_exercise", "Listening exercise"),
                            ("speaking_session", "Speaking session"),
                            ("writing_session", "Writing session"),
                            ("grammar_unit", "Grammar unit"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("target_key", models.CharField(db_index=True, max_length=255)),
                ("content", models.JSONField(blank=True, default=dict)),
                ("plain_text", models.TextField(blank=True)),
                ("title", models.CharField(blank=True, max_length=200)),
                ("target_url", models.CharField(blank=True, max_length=500)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="notes", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [models.Index(fields=["user", "-updated_at"], name="idx_note_user_updated")],
                "constraints": [
                    models.UniqueConstraint(fields=("user", "target_type", "target_key"), name="uniq_note_user_target")
                ],
            },
            bases=(backend.shared.infrastructure.sqlalchemy.tables.SQLAlchemyTableMixin, models.Model),
        ),
    ]
