"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

import cloudinary
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Corporate TLS interception (e.g. Zscaler) presents certs signed by a private
# root CA that certifi does not trust, breaking all outbound HTTPS. Set
# EXTRA_CA_CERTS to that root CA's PEM file and we merge it with certifi so
# `requests` trusts it. Works both on and off the VPN.
_EXTRA_CA_CERTS = os.getenv("EXTRA_CA_CERTS")
if _EXTRA_CA_CERTS and os.path.exists(_EXTRA_CA_CERTS):
    import tempfile

    import certifi

    _combined_ca_bundle = os.path.join(tempfile.gettempdir(), "flashlearn_ca_bundle.pem")
    try:
        with open(certifi.where(), "rb") as _f:
            _ca_data = _f.read()
        with open(_EXTRA_CA_CERTS, "rb") as _f:
            _extra_ca = _f.read()
        with open(_combined_ca_bundle, "wb") as _f:
            _f.write(_ca_data + b"\n" + _extra_ca)
        # requests/urllib honor these env vars automatically.
        os.environ["REQUESTS_CA_BUNDLE"] = _combined_ca_bundle
        os.environ["SSL_CERT_FILE"] = _combined_ca_bundle
    except OSError:
        pass

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False") == "True"

# Sentry monitoring for Django & RQ workers
SENTRY_DSN = os.getenv("SENTRY_DSN", "")
if SENTRY_DSN:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration
    from sentry_sdk.integrations.rq import RqIntegration

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[
            DjangoIntegration(),
            RqIntegration(),
        ],
        send_default_pii=True,
        enable_logs=True,
        traces_sample_rate=float(os.getenv("SENTRY_TRACES_SAMPLE_RATE", "1.0")),
        profile_session_sample_rate=float(os.getenv("SENTRY_PROFILE_SESSION_SAMPLE_RATE", "1.0")),
        profile_lifecycle="trace",
        environment=os.getenv("ENVIRONMENT", "development" if DEBUG else "production"),
    )

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "*").split(",")

# CORS_ALLOWED_ORIGINS = [
#     'http://localhost:3000',
#     'http://192.168.15.242:3000',
# ]

CORS_ALLOW_ALL_ORIGINS = os.getenv("CORS_ALLOW_ALL_ORIGINS", "False") == "True"
CORS_ALLOW_PRIVATE_NETWORK = True

# Required so the browser sends/stores the HttpOnly refresh cookie on cross-origin
# API calls (e.g. localhost:3000 -> localhost:8005 in dev, or the ngovandong
# subdomain split). With credentials, the matching origin must be explicit —
# a wildcard Access-Control-Allow-Origin is rejected by browsers.
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = os.getenv(
    "CORS_ALLOWED_ORIGINS",
    "http://localhost:3000,http://127.0.0.1:3000",
).split(",")

INTERNAL_IPS = [
    "127.0.0.1",
]

# Application definition

INSTALLED_APPS = [
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",
    "django_elasticsearch_dsl",
    "corsheaders",
    "drf_yasg",
    "revproxy",
    "channels",
    "django_rq",
    "base",
    "backend",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

if DEBUG:
    INSTALLED_APPS.insert(INSTALLED_APPS.index("corsheaders"), "debug_toolbar")
    MIDDLEWARE.insert(
        MIDDLEWARE.index("django.middleware.common.CommonMiddleware"),
        "debug_toolbar.middleware.DebugToolbarMiddleware",
    )

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"
ASGI_APPLICATION = "core.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [
                os.getenv("REDIS_URL") or (os.getenv("REDIS_HOST", "127.0.0.1"), int(os.getenv("REDIS_PORT", "6379")))
            ],
        },
    },
}

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT"),
        "OPTIONS": {
            "charset": "utf8",
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

USE_I18N = True

USE_TZ = True
TIME_ZONE = "Asia/Ho_Chi_Minh"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static")


# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "backend.User"

REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "core.authentication.CustomTokenAuthentication",
        "rest_framework.authentication.BasicAuthentication",
    ),
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "60/minute",
        "user": "300/minute",
    },
    "EXCEPTION_HANDLER": "backend.shared.interfaces.exception_handler.domain_exception_handler",
}


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),
    "ROTATE_REFRESH_TOKENS": True,
    # Kept False on purpose: the web app and browser extension can hold the same
    # refresh token, so blacklisting on every rotation would make one client log
    # the other out every ~30 min. Revocation is instead done explicitly on
    # logout via the /users/logout/ endpoint (which blacklists the refresh token).
    "BLACKLIST_AFTER_ROTATION": False,
    "UPDATE_LAST_LOGIN": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": None,
    "AUDIENCE": None,
    "ISSUER": None,
    "JWK_URL": None,
    "LEEWAY": 0,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",
    "JTI_CLAIM": "jti",
    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=5),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),
}

# --- Refresh-token cookie -----------------------------------------------------
# The refresh token is delivered to the SPA as an HttpOnly cookie (unreadable by
# JS, so an XSS can't exfiltrate it). The short-lived access token is returned in
# the response body and kept only in memory by the frontend. `/api/users/refresh`
# reads this cookie; `/api/users/logout` clears it + blacklists the token.
REFRESH_COOKIE_NAME = os.getenv("REFRESH_COOKIE_NAME", "refresh_token")
# Scope the cookie to the API path so it's only attached to backend calls.
REFRESH_COOKIE_PATH = "/api"
# Lax is safe here: the frontend talks to the API same-origin (via the /api proxy
# on Vercel) or cross-subdomain (same-site), and cross-site POSTs won't carry the
# cookie — which doubles as CSRF protection for the refresh endpoint.
REFRESH_COOKIE_SAMESITE = os.getenv("REFRESH_COOKIE_SAMESITE", "Lax")
# Secure (HTTPS-only) in production; relaxed for local http dev.
REFRESH_COOKIE_SECURE = os.getenv("REFRESH_COOKIE_SECURE", "False" if DEBUG else "True") == "True"
# load env
BASE_FRONTEND_URL = os.getenv("BASE_FRONTEND_URL")
BASE_BACKEND_URL = os.getenv("BASE_BACKEND_URL")
GOOGLE_OAUTH2_CLIENT_ID = os.getenv("GOOGLE_OAUTH2_CLIENT_ID")
GOOGLE_OAUTH2_CLIENT_SECRET = os.getenv("GOOGLE_OAUTH2_CLIENT_SECRET")
# Native iOS/Android Google Sign-In uses its own OAuth client IDs, so the ID
# tokens those apps mint carry a different `aud`. Accept them alongside the web
# client ID when validating ID tokens; web behavior is unchanged.
GOOGLE_OAUTH2_IOS_CLIENT_ID = os.getenv("GOOGLE_OAUTH2_IOS_CLIENT_ID")
GOOGLE_OAUTH2_ANDROID_CLIENT_ID = os.getenv("GOOGLE_OAUTH2_ANDROID_CLIENT_ID")
GOOGLE_OAUTH2_ALLOWED_AUDIENCES = [
    aud
    for aud in (
        GOOGLE_OAUTH2_CLIENT_ID,
        GOOGLE_OAUTH2_IOS_CLIENT_ID,
        GOOGLE_OAUTH2_ANDROID_CLIENT_ID,
    )
    if aud
]
# AI provider (provider-agnostic; AI_PROVIDER selects the concrete client)
AI_PROVIDER = os.getenv("AI_PROVIDER", "gemini")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
GEMINI_MODEL = os.getenv("GEMINI_MODEL", "gemini-3.1-flash-lite")
GEMINI_API_BASE = os.getenv("GEMINI_API_BASE", "https://generativelanguage.googleapis.com/v1beta")
# mail
EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", "core.email_backend.EmailBackend")
EMAIL_HOST = "smtp.gmail.com"
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False

# static file
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# cloudinary
cloudinary.config(
    cloud_name=os.environ.get("CLOUDINARY_CLOUD_NAME"),
    api_key=os.environ.get("CLOUDINARY_API_KEY"),
    api_secret=os.environ.get("CLOUDINARY_API_SECRET"),
)

BASE_CLOUDINARY_URL = f"https://res.cloudinary.com/{os.environ.get('CLOUDINARY_CLOUD_NAME')}/"

# Term images stored as base64 in the DB — compress when raw bytes exceed this limit
TERM_IMAGE_MAX_BYTES = int(os.getenv("TERM_IMAGE_MAX_BYTES", "200000"))
TERM_IMAGE_MAX_DIMENSION = int(os.getenv("TERM_IMAGE_MAX_DIMENSION", "800"))

if os.getenv("REDIS_URL"):
    RQ_QUEUES = {
        "default": {
            "URL": os.getenv("REDIS_URL"),
            "DEFAULT_TIMEOUT": 360,
        }
    }
else:
    RQ_QUEUES = {
        "default": {
            "HOST": os.environ.get("REDIS_HOST", "127.0.0.1"),
            "PORT": int(os.environ.get("REDIS_PORT", 6379)),
            "DB": 0,
            "DEFAULT_TIMEOUT": 360,
        }
    }


ELASTICSEARCH_DSL = {
    "default": {
        "hosts": f"{os.getenv('ELASTIC_SEARCH_HOST')}:{os.getenv('ELASTIC_SEARCH_PORT')}",
        # 'http_auth': (os.getenv('ELASTIC_SEARCH_USER'), os.getenv('ELASTIC_SEARCH_PASSWORD')),
    },
}

CACHE_TTL = 60 * 15

SKIP_REDIS = os.getenv("SKIP_REDIS")

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.getenv("REDIS_URL")
        or f"redis://{os.getenv('REDIS_HOST', '127.0.0.1')}:{os.getenv('REDIS_PORT', '6379')}/0",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        "file": {
            "level": "DEBUG",
            "class": "logging.FileHandler",
            "filename": "django_queries.log",
        },
    },
    "formatters": {
        "simple": {
            "format": "{asctime} {levelname} {name} — {message}",
            "style": "{",
        },
    },
    "loggers": {
        "django.db.backends": {
            "handlers": ["file"],
            "level": "DEBUG",
            "propagate": False,
        },
        "backend": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
