from typing import Any, Protocol


class CachePort(Protocol):
    def get(self, key: str) -> Any: ...

    def set(self, key: str, value: Any, timeout: int | None = None) -> None: ...

    def delete(self, key: str) -> None: ...

    def delete_pattern(self, pattern: str) -> None: ...


class ImageStoragePort(Protocol):
    def upload_bytes(self, data: bytes) -> str: ...

    def upload_file(self, file_obj) -> str: ...

    def url_to_base64(self, url: str) -> str: ...


class OAuthPort(Protocol):
    def validate_id_token(self, id_token: str) -> dict[str, Any]: ...

    def get_access_token(self, code: str, redirect_uri: str) -> str: ...

    def get_user_info(self, access_token: str) -> dict[str, Any]: ...
