from django.db import models

from base.models import DateTimeUUIDModel

from ..managers import TermManager
from ..term.domain.access import TermAccessPolicy
from .deck import Deck


class Term(DateTimeUUIDModel):
    name = models.CharField(max_length=255)
    # Native-language meaning / translation of the term (formerly `description`).
    meaning = models.TextField(blank=True)
    image = models.TextField(blank=True, null=True)
    # Oxford-dictionary-style data, typically generated by the AI enrichment service.
    word_type = models.CharField(max_length=50, blank=True)
    pronunciation = models.CharField(max_length=255, blank=True)
    definition = models.TextField(blank=True)
    synonyms = models.JSONField(default=list, blank=True)
    antonyms = models.JSONField(default=list, blank=True)
    examples = models.JSONField(default=list, blank=True)
    # Grammatical inflections of the same word, e.g. run ->
    # ["present participle: running", "past tense: ran", "past participle: run"].
    word_forms = models.JSONField(default=list, blank=True)
    # Related words in other parts of speech (word family), e.g. specify ->
    # ["noun: specification", "adverb: specifically"].
    word_family = models.JSONField(default=list, blank=True)
    # True once data has been populated by AI or manually overridden by a user;
    # the backfill cron skips terms where this is already set.
    ai_filled = models.BooleanField(default=False, db_index=True)
    deck = models.ForeignKey(Deck, on_delete=models.CASCADE, related_name="terms")

    objects = TermManager()

    class Meta:
        ordering = ["-created_at", "name"]

    def can_edit_term(self, user):
        return TermAccessPolicy.can_edit(self, user)
